[platformio]
src_dir = firmware/esp32_serial_spike
default_envs = robocore_wisdom_esp32

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = firmware/lib
build_flags =
  -DMLK_CONFIG_PARAMETER_SET=512
  -DMLK_CONFIG_NAMESPACE_PREFIX=PQC_SAT_MLKEM512
  -DWOLFSSL_USER_SETTINGS
  -Ifirmware/esp32_serial_spike
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200

[env:robocore_wisdom_esp32]
lib_ignore = wolfssl

[env:robocore_wisdom_esp32_fair]
build_flags =
  ${env.build_flags}
  -DPQC_SAT_ENABLE_FAIR_CRYPTO=1
  -DPQC_SAT_REQUIRE_FAIR_CRYPTO=1
