[platformio]
src_dir = firmware/esp32_serial_spike

[env:robocore_wisdom_esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
